import frappe

DEFAULTS = {"price_variance_warning_pct":5,"price_variance_critical_pct":10,"supplier_price_increase_warning_pct":8,"supplier_price_increase_critical_pct":15,"quantity_variance_warning_pct":2,"high_value_purchase_threshold":100000,"duplicate_invoice_check":1,"maverick_purchase_check":1,"supplier_price_intelligence":1,"automatic_scans":1,"scan_days":365,"auto_create_alerts":1}

def after_install():
    _ensure_settings(); _ensure_roles(); _ensure_custom_fields(); seed_demo_data(); frappe.clear_cache()

def after_migrate():
    _ensure_settings(); _ensure_roles(); _ensure_custom_fields(); seed_demo_data()

def _ensure_settings():
    if not frappe.db.exists("Purchase Guard Settings"):
        frappe.get_doc({"doctype":"Purchase Guard Settings",**DEFAULTS}).insert(ignore_permissions=True)
    else:
        doc=frappe.get_single("Purchase Guard Settings"); changed=False
        for field,value in DEFAULTS.items():
            if doc.get(field) in (None,""): doc.set(field,value); changed=True
        if changed: doc.save(ignore_permissions=True)

def _ensure_roles():
    for role in ("Purchase Guard Manager","Purchase Guard Analyst"):
        if not frappe.db.exists("Role",role): frappe.get_doc({"doctype":"Role","role_name":role,"desk_access":1}).insert(ignore_permissions=True)

def _ensure_custom_fields():
    fields=[
      {"dt":"Purchase Invoice","fieldname":"purchase_guard_section","label":"Purchase Guard","fieldtype":"Section Break"},
      {"dt":"Purchase Invoice","fieldname":"purchase_guard_summary","label":"Purchase Guard Analysis","fieldtype":"HTML"},
      {"dt":"Supplier","fieldname":"purchase_guard_supplier_section","label":"Purchase Guard","fieldtype":"Section Break"},
      {"dt":"Supplier","fieldname":"purchase_guard_supplier_summary","label":"Purchase Guard Intelligence","fieldtype":"HTML"},
    ]
    for row in fields:
        if not frappe.db.exists("Custom Field",{"dt":row["dt"],"fieldname":row["fieldname"]}): frappe.get_doc({"doctype":"Custom Field",**row}).insert(ignore_permissions=True)

def _make_supplier(name,group):
    if frappe.db.exists("Supplier",name): return name
    try: return frappe.get_doc({"doctype":"Supplier","supplier_name":name,"supplier_group":group,"supplier_type":"Company"}).insert(ignore_permissions=True).name
    except Exception: return None

def _make_item(code,group,uom):
    if frappe.db.exists("Item",code): return code
    try: return frappe.get_doc({"doctype":"Item","item_code":code,"item_name":code,"item_group":group,"stock_uom":uom,"is_stock_item":1}).insert(ignore_permissions=True).name
    except Exception: return None

def seed_demo_data():
    """Seed clearly-labelled Purchase Guard demo records once; do not fabricate ERPNext transactions."""
    if not frappe.db.exists("Company"): return
    if frappe.db.count("Supplier Risk Assessment",{"is_demo_data":1}) or frappe.db.count("Supplier Price Benchmark",{"is_demo_data":1}) or frappe.db.count("Purchase Risk Alert",{"is_demo_data":1}): return
    company=frappe.db.get_value("Company",{},"name"); group=frappe.db.get_value("Supplier Group",{},"name"); item_group=frappe.db.get_value("Item Group",{},"name"); uom=frappe.db.get_value("UOM",{},"name") or "Nos"
    if not company or not group or not item_group: return
    suppliers=[x for x in [_make_supplier(n,group) for n in ["ABC Industries (Demo)","XYZ Components (Demo)","PQR Manufacturing (Demo)","XYZ Metals (Demo)"]] if x]
    items=[x for x in [_make_item(n,item_group,uom) for n in ["Steel Sheet (Demo)","Copper Wire (Demo)","Bearing 6204 (Demo)","Industrial Valve (Demo)"]] if x]
    if not suppliers or not items: return
    from frappe.utils import add_days,today
    start=add_days(today(),-365); end=today()
    scores=[87,64,21,46]; spends=[4820000,2100000,1700000,1250000]; prices=[52,71,93,68]; invs=[62,78,96,81]; delivery=[83,88,92,76]; payment=[78,86,95,69]
    assessments=[]
    for i,s in enumerate(suppliers):
        score=scores[i]; assessments.append(frappe.get_doc({"doctype":"Supplier Risk Assessment","supplier":s,"company":company,"assessment_date":today(),"risk_score":score,"risk_level":"Critical" if score>=80 else "High" if score>=50 else "Medium" if score>=25 else "Low","purchase_spend":spends[i],"price_variance_items":3 if score>=60 else 1,"price_competitiveness_score":prices[i],"invoice_accuracy_score":invs[i],"delivery_performance_score":delivery[i],"payment_behavior_score":payment[i],"supplier_concentration_pct":round(spends[i]/10900000*100,2),"notes":"Demo assessment generated by Purchase Guard for evaluation. Replace with live ERPNext analysis.","is_demo_data":1}).insert(ignore_permissions=True))
    base_rates=[100, 80, 60, 350]
    supplier_multipliers=[1.34, 1.00, 0.96, 1.10]
    months=[6,5,4,3,2,1]
    from frappe.utils import add_months
    for si,supplier in enumerate(suppliers):
        for ii,item in enumerate(items):
            for mi,ago in enumerate(months):
                period_start=add_months(today(),-ago).replace(day=1)
                period_end=add_months(today(),-(ago-1)).replace(day=1) if ago>1 else today()
                trend=1 + (mi * 0.018 if ii==0 and si==0 else mi * 0.006)
                rate=round(base_rates[ii]*supplier_multipliers[si]*trend,2)
                qty=400 + si*100 + ii*50
                frappe.get_doc({
                    "doctype":"Supplier Price Benchmark","company":company,"item_code":item,"supplier":supplier,
                    "period_start":period_start,"period_end":period_end,"average_rate":rate,"minimum_rate":round(rate*0.98,2),
                    "maximum_rate":round(rate*1.02,2),"quantity_purchased":qty,"total_spend":qty*rate,
                    "variance_from_best_supplier_pct":round((supplier_multipliers[si]/min(supplier_multipliers)-1)*100,2),"is_demo_data":1
                }).insert(ignore_permissions=True)
    alerts=[
        ("Critical",94,"Supplier price anomaly","Current supplier rate is materially above the best observed comparable rate.","Renegotiate pricing and review recent purchase history.",842000,"Supplier Price Benchmark",None),
        ("Critical",91,"Duplicate invoice possibility","A near-duplicate supplier invoice pattern was detected in the demo dataset. This is demonstration-only; no ERPNext invoice is fabricated.","Verify supplier invoice number and supporting documents before payment.",421000,"Supplier",None),
        ("High",72,"Maverick purchase","Purchase activity was recorded without the expected purchase-order control. This is demonstration-only.","Confirm approval and commercial terms.",218000,"Supplier",None),
        ("High",68,"Price increase detected","Supplier pricing has increased beyond the configured warning threshold.","Compare alternative suppliers and negotiate the variance.",315000,"Supplier Price Benchmark",None),
        ("Medium",38,"High-value purchase review","Transaction exceeds the configured high-value purchase threshold. This is demonstration-only.","Confirm approval and supplier details.",125000,"Supplier",None),
    ]
    benchmark_names=frappe.get_all("Supplier Price Benchmark", filters={"is_demo_data":1}, pluck="name", limit_page_length=1)
    for i,(sev,score,title,evidence,action,amount,ref_dt,_) in enumerate(alerts):
        ref_name = benchmark_names[0] if ref_dt == "Supplier Price Benchmark" and benchmark_names else suppliers[i%len(suppliers)]
        frappe.get_doc({"doctype":"Purchase Risk Alert","company":company,"supplier":assessments[i%len(assessments)].supplier,"reference_doctype":ref_dt,"reference_name":ref_name,"risk_type":"Supplier Price Increase" if "price" in title.lower() else "Other","severity":sev,"risk_score":score,"amount":amount,"item_code":items[i%len(items)],"title":"Demo: "+title,"evidence":evidence,"recommended_action":action,"status":"Open","is_demo_data":1}).insert(ignore_permissions=True)
    frappe.db.commit()
