frappe.pages['purchase_guard_dashboard'].on_page_load = function(wrapper) {
    var page = frappe.ui.make_app_page({parent: wrapper, title: __('Purchase Guard'), single_column: true});
    page.main.html('<div class="purchase-guard-page"><div class="pg-loading">Loading Purchase Guard...</div></div>');
    load_dashboard(page);
};
function load_dashboard(page) {
    frappe.call({method:'purchase_guard.api.get_dashboard_data'}).then(function(r){ if(r.message) render_dashboard(page,r.message); });
}
function money(v){v=Number(v||0);if(Math.abs(v)>=10000000)return '₹'+(v/10000000).toFixed(2)+' Cr';if(Math.abs(v)>=100000)return '₹'+(v/100000).toFixed(2)+' L';return '₹'+Math.round(v).toLocaleString('en-IN');}
function esc(v){return $('<div>').text(v==null?'':v).html();}
function rc(s){s=Number(s||0);return s>=80?'critical':s>=50?'high':s>=25?'medium':'low';}
function render_dashboard(page,d){
 var a=d.alerts||[], n=d.anomalies||[], s=d.suppliers||[];
 var html=`<div class="purchase-guard-page"><div class="pg-hero"><div><div class="pg-eyebrow">PURCHASE PROTECTION</div><h1>Purchase Guard</h1><p>Find what deserves investigation before money leaves the business.</p></div><div class="pg-actions"><button class="btn btn-default btn-sm" id="pg-refresh">Refresh</button><button class="btn btn-primary btn-sm" id="pg-scan">Run Scan</button></div></div>
 <div class="pg-kpis">${kpi('Total Spend',money(d.total_spend),'Submitted purchase invoices')}${kpi('High Risk',money(d.high_risk_amount),d.high_risk_count+' high/critical findings')}${kpi('Open Alerts',d.open_alerts,'Needs review')}${kpi('Savings Risk',money(d.savings_risk),'Estimated avoidable spend')}</div>
 <div class="pg-grid"><section class="pg-card"><div class="pg-card-head"><div><h3>Critical Purchase Risks</h3><p>Highest priority findings</p></div><a href="#" id="pg-alerts-link">View all</a></div><div class="pg-table">${a.length?a.map(alert_row).join(''):empty('No open risk alerts')}</div></section>
 <section class="pg-card"><div class="pg-card-head"><div><h3>Risk Mix</h3><p>Current open alerts</p></div></div>${risk_mix(d.risk_mix)}</section>
 <section class="pg-card"><div class="pg-card-head"><div><h3>Price Anomalies</h3><p>Supplier prices that deserve attention</p></div><a href="#" id="pg-price-link">Price Intelligence</a></div><div class="pg-table">${n.length?n.map(anomaly_row).join(''):empty('No price anomalies yet')}</div></section>
 <section class="pg-card"><div class="pg-card-head"><div><h3>Supplier Intelligence</h3><p>Highest-risk suppliers</p></div><a href="#" id="pg-suppliers-link">View all</a></div>${s.length?s.map(supplier_row).join(''):empty('No supplier assessments yet')}</section></div></div>`;
 page.main.html(html);$('#pg-refresh').on('click',function(){load_dashboard(page);});$('#pg-scan').on('click',function(){frappe.call({method:'purchase_guard.api.run_scan',freeze:true,freeze_message:__('Scanning purchases...')}).then(function(){load_dashboard(page);});});$('#pg-alerts-link').on('click',function(e){e.preventDefault();frappe.set_route('List','Purchase Risk Alert');});$('#pg-price-link').on('click',function(e){e.preventDefault();frappe.set_route('price-intelligence');});$('#pg-suppliers-link').on('click',function(e){e.preventDefault();frappe.set_route('List','Supplier Risk Assessment');});page.main.find('.pg-open-reference').on('click',function(e){e.preventDefault();frappe.set_route('Form',$(this).data('doctype'),$(this).data('name'));});
}
function kpi(l,v,n){return `<div class="pg-kpi"><div class="pg-kpi-label">${l}</div><div class="pg-kpi-value">${v}</div><div class="pg-kpi-note">${n}</div></div>`;}function empty(t){return `<div class="pg-empty">${esc(t)}</div>`;}function alert_row(x){return `<div class="pg-row"><div><span class="pg-pill ${rc(x.risk_score)}">${esc(x.risk_score)}/100</span><strong>${esc(x.supplier||'—')}</strong><div class="pg-muted">${esc(x.title)}</div></div><div>${esc(x.reference_name||'—')}<div class="pg-muted">${esc(x.risk_type)}</div></div><div>${money(x.amount)}<div class="pg-muted">${esc(x.status)}</div></div><div><button class="btn btn-default btn-xs pg-open-reference" data-doctype="${esc(x.reference_doctype)}" data-name="${esc(x.reference_name)}">Investigate</button></div></div>`;}function anomaly_row(x){return `<div class="pg-row"><div><strong>${esc(x.item_code||'—')}</strong><div class="pg-muted">${esc(x.supplier||'—')}</div></div><div>Current<br><strong>${money(x.current_rate)}</strong></div><div>Normal<br><strong>${money(x.best_rate)}</strong></div><div><span class="pg-pill high">+${Number(x.variance_pct||0).toFixed(1)}%</span></div></div>`;}function supplier_row(x){return `<div class="pg-supplier"><div><strong>${esc(x.supplier)}</strong><div class="pg-muted">${money(x.purchase_spend)} spend</div></div><span class="pg-pill ${rc(x.risk_score)}">${esc(x.risk_score)}/100</span></div>`;}function risk_mix(m){return (m||[]).map(function(x){return `<div class="pg-mix"><div><span>${esc(x.label)}</span><strong>${x.count}</strong></div><div class="pg-bar"><span style="width:${Math.min(100,Number(x.count||0)/Math.max(1,Number(m[0]&&m[0].count||1))*100)}%"></span></div></div>`;}).join('');}
